name: Test

on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-18.04, fc: gfortran-5  }
          - { os: ubuntu-18.04, fc: gfortran-6  }
          - { os: ubuntu-18.04, fc: gfortran-7  }
          - { os: ubuntu-20.04, fc: gfortran-8  }
          - { os: ubuntu-22.04, fc: gfortran-9  }
          - { os: ubuntu-22.04, fc: gfortran-10 }
          - { os: ubuntu-22.04, fc: gfortran-11 }
          - { os: ubuntu-22.04, fc: gfortran-12 }
          - { os: ubuntu-22.04, fc: gfortran-11, build-type: coverage }

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up fpm
        uses: fortran-lang/setup-fpm@v4
        with:
          fpm-version: v0.5.0

      - name: Set up Fortran
        uses: tueda/setup-fortran@v1
        with:
          fortran-compiler: ${{ matrix.fc }}

      - name: Run test
        if: matrix.build-type != 'coverage'
        run: fpm test
        env:
          FPM_FC: ${{ matrix.fc }}

      - name: Run test (with coverage)
        if: matrix.build-type == 'coverage'
        run: fpm test
        env:
          FPM_FC: ${{ matrix.fc }}
          FPM_FFLAGS: -coverage -g -fcheck=bounds -fcheck=array-temps -fbacktrace

      - name: Run gcov
        if: matrix.build-type == 'coverage'
        run: $find . -type f -name '*.gcno' -exec $GCOV -pb {} +

      - name: Upload coverage report
        if: matrix.build-type == 'coverage'
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true